source 'https://github.com/CocoaPods/Specs.git'

target 'ROSiOS', :exclusive => true do
  pod "ROSiOS", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ROSiOS", :path => "../"

  
end
