/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /Users/furushchev/Development/jsk_smart_apps_orig/jsk_ios_utils/ros/geometry/tf/srv/FrameGraph.srv
 *
 */


#ifndef TF_MESSAGE_FRAMEGRAPH_H
#define TF_MESSAGE_FRAMEGRAPH_H

#include <ros/service_traits.h>


#include <tf/FrameGraphRequest.h>
#include <tf/FrameGraphResponse.h>


namespace tf
{

struct FrameGraph
{

typedef FrameGraphRequest Request;
typedef FrameGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FrameGraph
} // namespace tf


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tf::FrameGraph > {
  static const char* value()
  {
    return "c4af9ac907e58e906eb0b6e3c58478c0";
  }

  static const char* value(const ::tf::FrameGraph&) { return value(); }
};

template<>
struct DataType< ::tf::FrameGraph > {
  static const char* value()
  {
    return "tf/FrameGraph";
  }

  static const char* value(const ::tf::FrameGraph&) { return value(); }
};


// service_traits::MD5Sum< ::tf::FrameGraphRequest> should match 
// service_traits::MD5Sum< ::tf::FrameGraph > 
template<>
struct MD5Sum< ::tf::FrameGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tf::FrameGraph >::value();
  }
  static const char* value(const ::tf::FrameGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf::FrameGraphRequest> should match 
// service_traits::DataType< ::tf::FrameGraph > 
template<>
struct DataType< ::tf::FrameGraphRequest>
{
  static const char* value()
  {
    return DataType< ::tf::FrameGraph >::value();
  }
  static const char* value(const ::tf::FrameGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tf::FrameGraphResponse> should match 
// service_traits::MD5Sum< ::tf::FrameGraph > 
template<>
struct MD5Sum< ::tf::FrameGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tf::FrameGraph >::value();
  }
  static const char* value(const ::tf::FrameGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tf::FrameGraphResponse> should match 
// service_traits::DataType< ::tf::FrameGraph > 
template<>
struct DataType< ::tf::FrameGraphResponse>
{
  static const char* value()
  {
    return DataType< ::tf::FrameGraph >::value();
  }
  static const char* value(const ::tf::FrameGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TF_MESSAGE_FRAMEGRAPH_H
