/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /Users/furushchev/Development/ros_for_ios/ros/common_msgs/nav_msgs/srv/GetMap.srv
 *
 */


#ifndef NAV_MSGS_MESSAGE_GETMAP_H
#define NAV_MSGS_MESSAGE_GETMAP_H

#include <ros/service_traits.h>


#include <nav_msgs/GetMapRequest.h>
#include <nav_msgs/GetMapResponse.h>


namespace nav_msgs
{

struct GetMap
{

typedef GetMapRequest Request;
typedef GetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMap
} // namespace nav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_msgs::GetMap > {
  static const char* value()
  {
    return "6cdd0a18e0aff5b0a3ca2326a89b54ff";
  }

  static const char* value(const ::nav_msgs::GetMap&) { return value(); }
};

template<>
struct DataType< ::nav_msgs::GetMap > {
  static const char* value()
  {
    return "nav_msgs/GetMap";
  }

  static const char* value(const ::nav_msgs::GetMap&) { return value(); }
};


// service_traits::MD5Sum< ::nav_msgs::GetMapRequest> should match 
// service_traits::MD5Sum< ::nav_msgs::GetMap > 
template<>
struct MD5Sum< ::nav_msgs::GetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_msgs::GetMap >::value();
  }
  static const char* value(const ::nav_msgs::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_msgs::GetMapRequest> should match 
// service_traits::DataType< ::nav_msgs::GetMap > 
template<>
struct DataType< ::nav_msgs::GetMapRequest>
{
  static const char* value()
  {
    return DataType< ::nav_msgs::GetMap >::value();
  }
  static const char* value(const ::nav_msgs::GetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_msgs::GetMapResponse> should match 
// service_traits::MD5Sum< ::nav_msgs::GetMap > 
template<>
struct MD5Sum< ::nav_msgs::GetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_msgs::GetMap >::value();
  }
  static const char* value(const ::nav_msgs::GetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_msgs::GetMapResponse> should match 
// service_traits::DataType< ::nav_msgs::GetMap > 
template<>
struct DataType< ::nav_msgs::GetMapResponse>
{
  static const char* value()
  {
    return DataType< ::nav_msgs::GetMap >::value();
  }
  static const char* value(const ::nav_msgs::GetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_MSGS_MESSAGE_GETMAP_H
